### ISSUE TITLE
Déclencheurs doods

### ISSUE THREAD

**Issue by cob94440** [herveaurel/Docs#1]
Bonjour,

J'essaie de comprendre le fonctionnement. Ton declencheur pour prendre les captures c'est dans le cas où l'alarme est active deux portes. C'est quel que soit l'état ou juste lors d'un changement d'état passant de on à off?

**Comment by herveaurel** [comment]
Moi j'essaie de comprendre ta question... 
Dans le doute : je prends des captures peu importe l'état de l'alarme. Les déclencheurs sont en général un mouvement, une porte qui s'ouvre, ou une serrure qui se déverrouille. 
Ensuite sur mon tableau de bord et maintenant sur Telegram qui me sert de journal, je trie les capture selon l'état de l'alarme.

**Comment by cob94440** [comment]
Merci pour ce premier retour,
Pour expliquer, dans ton automatisation en trigger je vois 👍 
```
trigger:
  - platform: state
    entity_id:
      - binary_sensor.porte_cagibi
      - binary_sensor.porte_entree
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.porte_entree
      - binary_sensor.porte_cagibi
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
```


Si je comprends l'automatisation se déclenche à ouverture et aussi à fermeture de ces deux portes c'est bien ça?
En Remplacement sur ma caméra exterieur je pourrais ne mettre que détection de mouvement?

**Comment by herveaurel** [comment]
Il ne s'agit pas de mon (mes) auto finale que j'utilise. Mais dans cette exemple oui les déclencheurs sont les états on et off des devices. 
Mais évidement tu mets ce que tu veux en déclencheur, ce qui est tout le principe et l'avantage du système. 
Dans certaines pièces ou endroits, ça peut être un mouvement, une serrure, une porte. Voir plusieurs déclencheurs même. 
À toi de voir ce qui doit déclencher la prise de photo pour le contrôle de présence humaine.

**Comment by cob94440** [comment]
Bonsoir, dans le script exemple il y a cette commande shell:  shell_command.copy_entree_video

A quoi correspond elle stp.

**Comment by cob94440** [comment]
J'ai fait ça en adaptation. C'est correct selon toi? Désolé des questions. je suis plutôt à l'aise avec ton dashboard un peu moins en automatisations.
```
alias: Camera entrée snapshot détection avec alarme
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.nvr_motion
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.nvr_motion
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.maison
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.maison
        state: arming
action:
  - service: camera.snapshot
    target:
      entity_id: camera.nvr_sub
    data:
      filename: /media/detections/captures/entreealarme_detection.jpg
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.doods_entreealarme_detection
  - repeat:
      count: "10"
      sequence:
        - if:
            - condition: numeric_state
              entity_id: image_processing.doods_entreealarme_detection
              below: 1
          then:
            - delay:
                hours: 0
                minutes: 0
                seconds: 2
                milliseconds: 0
            - service: camera.snapshot
              target:
                entity_id: camera.nvr_sub
              data:
                filename: /media/detections/captures/entreealarme_detection.jpg
            - delay:
                hours: 0
                minutes: 0
                seconds: 0
                milliseconds: 500
            - service: image_processing.scan
              data: {}
              target:
                entity_id: image_processing.doods_entreealarme_detection
          else:
            - service: input_text.set_value
              data:
                value: "{{ now().strftime(\"%d/%m - %H:%M\") }}"
              target:
                entity_id: input_text.horodatage_cam_entree_alarme
            - service: notify.mobile_app_honor
              data:
                message: "Personne détectée ! "
                title: Entrée 📸
                data:
                  image: /media/local/detections/captures/entreealarme_detection.jpg
                  push:
                    sound:
                      name: default
                      critical: 1
                      volume: 0
                  actions:
                    - action: DESACTIVER_ALARME
                      title: 🏠 Désactiver l'alarme
                      destructive: true
                    - action: ACTIVER_ALARME
                      title: 🚨 Activer l'alarme
                      destructive: false
                    - action: RIEN
                      title: Annuler
            - service: camera.record
              data:
                lookback: 30
                filename: /media/detections/captures/detection.mp4
                duration: 20
              target:
                entity_id: camera.nvr_sub
            - delay:
                hours: 0
                minutes: 0
                seconds: 25
                milliseconds: 0
            - service: notify.mobile_app_honor
              data:
                message: "Vidéo ! "
                title: Entrée 🎬
                data:
                  video: /media/local/detections/captures/detection.mp4
                  push:
                    sound:
                      name: default
                      critical: 1
                      volume: 0
                  actions:
                    - action: DESACTIVER_ALARME
                      title: 🏠 Désactiver l'alarme
                      destructive: true
                    - action: ACTIVER_ALARME
                      title: 🚨 Activer l'alarme
                      destructive: false
                    - action: RIEN
                      title: Annuler
            - service: shell_command.copy_entree_video
              data: {}
            - stop: Détection réussie
mode: single
```
